language: java
sudo: false
install: true

jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "iwakoshi"
    token:
      secure: $SONAR_TOKEN
      
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

script:
 - mvn -B -V clean
 - mvn -B -V build
 - mvn -B -V org.jacoco:jacoco-maven-plugin:prepare-agent test  # JaCoCo is used to have code coverage, the agent has to be activated
 - mvn -B -V sonar:sonar
 - mvn -B -V install -DskipTests=true -Dmaven.javadoc.skip=true
